### ISSUE TITLE
Make sudo call in gamepad_launcher.service non-interactive

### ISSUE THREAD

**Issue by NateTheGreat68** [NateTheGreat68/gamepad-launcher#10]
Is currently `ExecStop=sudo systemctl restart xow`; consider adding -n option to sudo to force non-interactive. Also should probably be ExecStopPost instead of ExecStop.

**Comment by NateTheGreat68** [comment]
Can't change the directive from ExecStop to ExecStopPost because the unit file has to have at least one of ExecStart or ExecStop (or SuccessAction). I'll leave it as ExecStop but add the -n option.

**Comment by NateTheGreat68** [comment]
Pulled into dev; closing.

**Comment by kakra** [comment]
Ah okay... But oneshot units don't need a stop. So if your ExecStart process isn't forking, you could use ExecStartPost maybe?

**Comment by NateTheGreat68** [comment]
I think you may be confusing this with your comment on one of the commits regarding using ExecStop within steam_bigpicture.service to stop the main gamepad_launcher.service file. I just made that change and merged it into the dev branch, but this is something different.
